In [2]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 55,  69,  71,  91,  77],
       [ 83,  96,  67,  72,  99],
       [ 64,  73,  65,  90,  55],
       [ 64,  70,  82,  65,  81],
       [ 62,  74,  73,  55,  52],
       [ 93,  85,  64,  99,  84],
       [ 77,  72,  53,  73,  58],
       [ 55,  79,  51,  96,  70],
       [ 61,  98,  73,  72,  67],
       [ 86,  71,  60,  65,  61],
       [ 71,  68,  64,  85,  97],
       [ 93,  59,  61,  56,  95],
       [ 75,  55,  55,  62,  62],
       [ 79,  95,  64,  74,  66],
       [ 58,  60,  69,  81,  70],
       [ 79,  57,  97,  78,  62],
       [ 89,  81,  95,  84,  59],
       [ 76,  72,  50,  89, 100],
       [ 70,  90,  65,  90,  95],
       [ 63,  53,  88,  89,  64],
       [ 53,  65,  67,  86,  52],
       [ 56,  54,  91,  52,  55],
       [ 73,  79,  54,  63,  97],
       [ 85,  87,  98,  55,  53],
       [ 51,  67,  58,  81,  95],
       [ 84,  57,  99,  71,  89],
       [ 87,  89,  62,  68,  93],
       [ 54,  82,  85,  50,  54],
       [ 93,  72,  56,  80,  58],
       [ 59,  

In [3]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[64, 66, 80, 62, 75],
       [74, 96, 63, 82, 67],
       [90, 64, 78, 97, 97],
       [59, 83, 92, 54, 72],
       [63, 78, 62, 84, 51]])

In [4]:
np.sum(students,axis=1) #每個學生的總分
np.mean(students,axis=1) #每個學生的平均
np.max(students,axis=1) #每個學生的最高分
np.min(students,axis=1) #每個學生的最低分
np.argmax(students,axis=1) #每個學生的最高分的科目
np.argmin(students,axis=1) #每個學生的最低分的科目
np.median(students,axis=1) #每個學生的中位數

array([71., 83., 65., 70., 62., 85., 72., 70., 72., 65., 71., 61., 62.,
       74., 69., 78., 84., 76., 90., 64., 65., 55., 73., 85., 67., 84.,
       87., 54., 72., 81., 60., 64., 74., 80., 79., 70., 79., 81., 80.,
       59., 83., 72., 59., 88., 88., 66., 74., 90., 72., 63.])